/*
This file is part of CanFestival, a library implementing CanOpen Stack. 

Copyright (C): Edouard TISSERANT and Francis DUPIN

See COPYING file for copyrights details.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#ifndef __objdictdef_h__
#define __objdictdef_h__

/************************* CONSTANTES **********************************/
/** this are static defined datatypes taken fCODE the canopen standard. They
 *  are located at index 0x0001 to 0x001B. As described in the standard, they
 *  are in the object dictionary for definition purpose only. a device does not
 *  to support all of this datatypes.
 */
#define boolean         0x01
#define int8            0x02
#define int16           0x03
#define int32           0x04
#define uint8_t         0x05
#define uint16          0x06
#define uint32          0x07
#define real32          0x08
#define visible_string  0x09
#define octet_string    0x0A
#define unicode_string  0x0B
#define time_of_day     0x0C
#define time_difference 0x0D

#define domain          0x0F
#define int24           0x10
#define real64          0x11
#define int40           0x12
#define int48           0x13
#define int56           0x14
#define int64           0x15
#define uint24          0x16

#define uint40          0x18
#define uint48          0x19
#define uint56          0x1A
#define uint64          0x1B

#define pdo_communication_parameter 0x20
#define pdo_mapping                 0x21
#define sdo_parameter               0x22
#define identity                    0x23

#define negt_procduce               0x40 /* 本公司标定类型，带一个参数(两字节)的函数 */

/* CanFestival is using 0x24 to 0xFF to define some types containing a 
   value range (See how it works in objdict.c)
 */

/** definitions of the different types of PDOs' transmission
 * 
 * SYNCHRO(n) means that the PDO will be transmited every n SYNC signal.
 */
#define TRANS_EVERY_N_SYNC(n) (n) /*n = 1 to 240 */
#define TRANS_SYNC_MIN        1    /* Trans after reception of n SYNC. n = 1 to 240 */
#define TRANS_SYNC_MAX        240  /* Trans after reception of n SYNC. n = 1 to 240 */
#define TRANS_RTR_SYNC        252  /* Transmission on request */
#define TRANS_RTR             253  /* Transmission on request */
#define TRANS_EVENT           255  /* Transmission on event */

/** Each entry of the object dictionary can be READONLY (RO), READ/WRITE (RW),
 *  WRITE-ONLY (WO)
 */
#define RW     0x00  
#define WO     0x01
#define RO     0x02

#define TO_BE_SAVED  0x04

/************************ STRUCTURES ****************************/
/**
Constant dictionary structure
 */
typedef struct s_dict_cste
{
	/** defines the last available entry of the communication profile
	 *  area. Adjust this var, if you have additional enties.
	 */
	UNS16 comm_profile_last;

	/** This is the last defined entry for sdo-paramters.
	 *  This means: this is the last entry for which memory
	 *  has been allocated. Adjust this value if you need more
	 *  or less entries.
	 */
	UNS16 server_SDO_last;

	/** indicates the count of defined PDOs
	 */
	UNS16 max_count_of_server_SDO;

	UNS16 client_SDO_last;

	UNS16 max_count_of_client_SDO;

	/** This is the last defined entry for pdo-paramters (rx).
	 *  This means: this is the last entry for which memory
	 *  has been allocated. Adjust this value if you need more
	 *  or less entries.
	 */
	UNS16 receive_PDO_last;

	/** Autogenerated value: indicates the count of defined PDOs
	 *  for reception
	 */
	UNS16 max_count_of_PDO_receive;

	/** This is the last defined entry for pdo-paramters (tx).
	 *  This means: this is the last entry for which memory
	 *  has been allocated. Adjust this value if you need more
	 *  or less entries.
	 */
	UNS16 transmit_PDO_last;

	/** Indicates the count of defined PDOs
	 *  for tramsmission
	 */
	UNS16 max_count_of_PDO_transmit;

	/** This is the last PDO-Mapping parameter (rx) for which memory
	 *  has been allocated
	 */
	UNS16 receive_PDO_mapping_last;

	/** This is the last PDO-Mapping parameter (tx) for which memory
	 *  has been allocated
	 */
	UNS16 transmit_PDO_mapping_last;

	/** This is the last manufacturer specific data table for which memory
	 *  has been allocated
	 */
	UNS16 manufacturerSpecificLastIndex;

	/** This is the last digital Input Table Index for which memory
	 *  has been allocated
	 */
	UNS16 digitalInputTableLastIndex;

	/** This is the last digital Output Table Index for which memory
	 *  has been allocated
	 */
	UNS16 digitalOutputTableLastIndex;

	/** Number of nodes from which can be received a heartbeat
	 */
	UNS8 nbOfHeartbeatProducers;
}dict_cste;

/** This is the datatype for the communication parameter of PDOs defined
 *  by the CANopen standard
 */
typedef struct td_s_pdo_communication_parameter  // Index: 0x20
{
    /** number of supported entries = nb subindex - 1
     */
    UNS8   count;
    /** COB-ID
     */
    UNS32  cob_id;
    /** transmission type: 
  	255 (0XFF) : Transmission on event
  	253 (0XFD) : Transmission on request. Use instead the #define RTR 253
    1 - 240    : Transmission on synchro. Use instead the macro SYNCHRO(n)
             n : to transmit every n SYNC message.
     */
    UNS8   type;
    /** inhibit time: not supported yet.
     */
    UNS16  inhibit_time;
    /** reserved (by CANopen standard)
     */
    UNS8   reserved;
    /** event timer: not supported yet.
     */
    UNS16  event_timer;
} s_pdo_communication_parameter;

// s_pdo_mapping_parameter // Index: 0x21 is defined in objdict.c
// ---------------------------------------------------------------

/** Struct needed for SDO parameter. Defined by the CANopen standard
 */
typedef struct td_s_sdo_parameter // Index: 0x22
{
    /** number of supported entries
     */
    UNS8   count;
    /** COB-ID client->server
     */
    UNS32  cob_id_client;
    /** COB-ID server->client
     */
    UNS32  cob_id_server;
    /** node ID of SDO's client resp. server
     */
    UNS8   node_id;
} s_sdo_parameter;

/** Struct needed for the idendity of a CANopen device. Defined
 *  by the CANopen standard
 */
typedef struct td_s_identity  // Index: 0x23
{
    /** number of supported entries
     */
    UNS8   count;
    /** Vendor-ID (given by the CAN-CIA)
     */
    UNS32  vendor_id;
    /** Product code
     */
    UNS32  product_code;
    /** Revision number
     */
    UNS32  revision_number;
    /** Serial number of this device
     */
    UNS32  serial_number;
} s_identity;

/************************ STRUCTURES ****************************/
/** This are some structs which are neccessary for creating the entries
 *  of the object dictionary.
 */
typedef void (*SaveProcFun)(void);

typedef struct td_subindex
{
    UNS8  bAccessType;
    UNS8  bDataType; /* Defines of what datatype the entry is */
    UNS8  size;      /* The size (in Byte) of the variable */
    void* pObject;   /* This is the pointer of the Variable */
	SaveProcFun pSaveProc; /* Save parameter produce */
}subindex;

/** Struct for creating entries in the communictaion profile
 */
typedef struct td_indextable
{
    subindex *pSubindex;  /* Pointer to the subindex */
    UNS8  bSubCount;      /* the count of valid entries for this subindex
                           * This count here defines how many memory has been
                           * allocated. this memory does not have to be used.
                          */
    UNS16 index;
}indextable;

typedef struct s_quick_index{
	UNS16 SDO_SVR;
	UNS16 SDO_CLT;
	UNS16 PDO_RCV;
	UNS16 PDO_RCV_MAP;
	UNS16 PDO_TRS;
	UNS16 PDO_TRS_MAP;
}quick_index;

/************************** MACROS *********************************/

#define DeclareIndexTableEntry(entryname)   { (subindex*)entryname, sizeof(entryname)/sizeof(entryname[0]) }

/* CANopen usefull helpers */
#define GET_NODE_ID(m)         (m.cob_id.w & 0x7f)
#define GET_FUNCTION_CODE(m)     (m.cob_id.w >> 7)

#endif /* __objdictdef_h__ */

